# ==========================================
# CONEXÃO COM SUPABASE (POSTGRESQL)
# ==========================================
spring.datasource.url=jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres.omorauijvkkzdhcpasho
spring.datasource.password=Vetor@20252026
# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Desativa H2 e Flyway
spring.h2.console.enabled=false
spring.flyway.enabled=false

# Logs de Segurança
logging.level.org.springframework.security=DEBUG
logging.level.com.example.demo=DEBUG

# Argon2id Params
security.argon2.salt-length=16
security.argon2.hash-length=32
security.argon2.parallelism=1
security.argon2.memory=65536
security.argon2.iterations=3