spring.application.name=demo
server.servlet.session.timeout=15m

#Argon2id Params (Requisitos 1.1 e 1.2)

security.argon2.salt-length=16
security.argon2.hash-length=32
security.argon2.parallelism=1
security.argon2.memory=65536
security.argon2.iterations=3